#!/usr/bin/env bash
# Installing Nginx on Server
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx start
