#!/usr/bin/env bash
# a bash script that :
# 1 : Creates the file /var/run/holbertonscript.pid containing its PID
# 2 : Displays To infinity and beyond indefinitely
# 3 : Displays I hate the kill command when receiving a SIGTERM signal
# 4 : Displays Y U no love me?! when receiving a SIGINT signal
# 5 : Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2

done