#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations
i=0
while [ "$i" -le "9" ]
do
  echo "Holberton School"
  if [ "$i" -eq "3" ]
  then
    echo "bad luck"
  elif [ "$i" -eq "7" ]
  then
    echo "good luck"  
  fi
((i=i+1))
done
