#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
a=0
while [ $a -le 12 ]
do
  echo "Hour: $a"
  b=1
  while [ $b -le 59 ]
  do
    echo $b
    ((b=b+1))
  done
  ((a=a+1))
done